# Generated by Django 3.0 on 2021-09-28 07:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('account_no', models.CharField(max_length=400)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CashPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ClearingPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DiscountPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FreightPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='IncentivePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=50, null=True)),
                ('transaction_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=50)),
                ('total_amount', models.FloatField(null=True)),
                ('net_balance', models.FloatField(blank=True, default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('area', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=13)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('SCI', models.ImageField(blank=True, null=True, upload_to='')),
                ('TOR', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Category')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DiscountCategory')),
            ],
        ),
        migrations.CreateModel(
            name='PartyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('freight', models.FloatField(default=0)),
                ('total_amount', models.FloatField()),
                ('discounted_amount', models.FloatField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Party')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('commission', models.FloatField(default=0.0)),
                ('contact', models.CharField(max_length=13)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opening_Balance', models.FloatField()),
                ('current_Balance', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BankLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Ledger')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Bank')),
            ],
            bases=('app.ledger',),
        ),
        migrations.CreateModel(
            name='CashLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Ledger')),
                ('cash_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CashPerson')),
            ],
            bases=('app.ledger',),
        ),
        migrations.CreateModel(
            name='ClearingLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Ledger')),
                ('clearing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ClearingPerson')),
            ],
            bases=('app.ledger',),
        ),
        migrations.CreateModel(
            name='DiscountLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Ledger')),
                ('discounted_amount', models.FloatField()),
                ('discount_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DiscountPerson')),
            ],
            bases=('app.ledger',),
        ),
        migrations.CreateModel(
            name='FreightLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Ledger')),
                ('freight', models.FloatField()),
                ('freight_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FreightPerson')),
            ],
            bases=('app.ledger',),
        ),
        migrations.CreateModel(
            name='IncentiveLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Ledger')),
                ('incentive_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.IncentivePerson')),
            ],
            bases=('app.ledger',),
        ),
        migrations.CreateModel(
            name='PartyLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Ledger')),
                ('freight', models.FloatField(blank=True, null=True)),
            ],
            bases=('app.ledger',),
        ),
        migrations.CreateModel(
            name='SalesOfficerLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Ledger')),
                ('party_order', models.IntegerField(blank=True, null=True)),
                ('sales_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SalesOfficer')),
            ],
            bases=('app.ledger',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('default_price', models.FloatField(blank=True, default=0)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PartyOrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('party_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PartyOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
        migrations.AddField(
            model_name='partyorder',
            name='sale_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SalesOfficer'),
        ),
        migrations.AddField(
            model_name='party',
            name='sales_Officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.SalesOfficer'),
        ),
        migrations.CreateModel(
            name='ExpectedCustomers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('Farmer', 'Farmer'), ('Dealer', 'Dealer'), ('Distributer', 'Distributer')], max_length=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50)),
                ('monthly_rage', models.IntegerField()),
                ('attached_company', models.CharField(max_length=300)),
                ('response', models.CharField(max_length=1000)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.DiscountCategory')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOfficerReceiving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Clearing', 'Clearing')], max_length=20)),
                ('recieved_amount', models.FloatField()),
                ('description', models.CharField(max_length=50)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Bank')),
                ('sale_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SalesOfficer')),
                ('bl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.BankLedger')),
                ('cl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CashLedger')),
                ('cll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ClearingLedger')),
                ('sol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.SalesOfficerLedger')),
            ],
        ),
        migrations.CreateModel(
            name='SalesLedger',
            fields=[
                ('ledger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Ledger')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SalesPerson')),
            ],
            bases=('app.ledger',),
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Clearing', 'Clearing')], max_length=20)),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=50)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Bank')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Party')),
                ('party_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PartyOrder')),
                ('sale_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SalesOfficer')),
                ('bl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.BankLedger')),
                ('cl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CashLedger')),
                ('cll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ClearingLedger')),
                ('pl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PartyLedger')),
            ],
        ),
        migrations.AddField(
            model_name='partyorder',
            name='dl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DiscountLedger'),
        ),
        migrations.AddField(
            model_name='partyorder',
            name='fl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FreightLedger'),
        ),
        migrations.AddField(
            model_name='partyorder',
            name='il',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.IncentiveLedger'),
        ),
        migrations.AddField(
            model_name='partyorder',
            name='plc1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.PartyLedger'),
        ),
        migrations.AddField(
            model_name='partyorder',
            name='plc2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.PartyLedger'),
        ),
        migrations.AddField(
            model_name='partyorder',
            name='pld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.PartyLedger'),
        ),
        migrations.AddField(
            model_name='partyorder',
            name='sl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.SalesLedger'),
        ),
        migrations.AddField(
            model_name='partyorder',
            name='sol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.SalesOfficerLedger'),
        ),
        migrations.AddField(
            model_name='partyledger',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Party'),
        ),
        migrations.AddField(
            model_name='partyledger',
            name='sales_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SalesOfficer'),
        ),
    ]
