# Generated by Django 3.0 on 2021-09-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210928_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='SCI',
            field=models.ImageField(blank=True, null=True, upload_to='Security Check Images'),
        ),
        migrations.AlterField(
            model_name='party',
            name='TOR',
            field=models.ImageField(blank=True, null=True, upload_to='Terms of Recoreds'),
        ),
    ]
