# Generated by Django 3.1.12 on 2021-10-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210930_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyorder',
            name='pandding_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
