# Generated by Django 3.1.12 on 2021-10-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_partyorder_pandding_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
