# Generated by Django 3.1.12 on 2021-10-12 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_party_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyorder',
            name='pld',
        ),
        migrations.AddField(
            model_name='partyorder',
            name='pl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.partyledger'),
        ),
        migrations.AlterField(
            model_name='partyorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
