# Generated by Django 3.1.12 on 2021-10-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211012_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyorder',
            name='dl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.discountledger'),
        ),
        migrations.AlterField(
            model_name='partyorder',
            name='fl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.freightledger'),
        ),
        migrations.AlterField(
            model_name='partyorder',
            name='il',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.incentiveledger'),
        ),
        migrations.AlterField(
            model_name='partyorder',
            name='pl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.partyledger'),
        ),
        migrations.AlterField(
            model_name='partyorder',
            name='plc1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.partyledger'),
        ),
        migrations.AlterField(
            model_name='partyorder',
            name='plc2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.partyledger'),
        ),
        migrations.AlterField(
            model_name='partyorder',
            name='sl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.salesledger'),
        ),
        migrations.AlterField(
            model_name='partyorder',
            name='sol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.salesofficerledger'),
        ),
    ]
