# Generated by Django 3.1.12 on 2021-10-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_dispatchtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchtable',
            name='locations',
            field=models.TextField(null=True),
        ),
    ]
