# Generated by Django 3.1.12 on 2021-10-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_dispatchtable_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchtable',
            name='freight',
            field=models.IntegerField(default=0),
        ),
    ]
