# Generated by Django 3.1.12 on 2021-10-15 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211015_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='sales_Officer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.salesofficer'),
            preserve_default=False,
        ),
    ]
