# Generated by Django 3.1.12 on 2021-10-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211015_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='sales_Officer',
            new_name='sale_officer',
        ),
    ]
