# Generated by Django 3.1.12 on 2021-10-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20211015_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='Kg', max_length=30),
        ),
    ]
