# Generated by Django 3.1.12 on 2021-10-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='region',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='zone',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
