# Generated by Django 3.1.12 on 2021-10-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20211016_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='SCI',
            field=models.FileField(blank=True, null=True, upload_to='Security Check Images'),
        ),
        migrations.AlterField(
            model_name='party',
            name='TOR',
            field=models.FileField(blank=True, null=True, upload_to='Terms of Recoreds'),
        ),
    ]
