# Generated by Django 3.1.12 on 2021-10-26 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211023_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyledger',
            name='sales_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.salesofficer'),
        ),
    ]
