# Generated by Django 3.1.12 on 2021-10-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20211026_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyorder',
            name='gross_total',
            field=models.FloatField(default=0),
        ),
    ]
