# Generated by Django 3.1.12 on 2021-10-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_partyorder_gross_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyorder',
            name='locations',
            field=models.TextField(default=''),
        ),
    ]
