# Generated by Django 3.1.12 on 2021-10-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_partyorder_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovery',
            name='sl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.salesofficerledger'),
        ),
        migrations.AlterField(
            model_name='recovery',
            name='payment_method',
            field=models.CharField(choices=[('SalesOfficer', 'SalesOfficer'), ('Cash', 'Cash'), ('Bank', 'Bank'), ('Clearing', 'Clearing')], max_length=20),
        ),
    ]
