# Generated by Django 3.1.12 on 2021-11-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20211118_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='description',
            field=models.CharField(max_length=300000, null=True),
        ),
    ]
