# Generated by Django 3.1.12 on 2021-11-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20211118_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovery',
            name='description',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
    ]
